# Generated by Django 4.1.4 on 2024-06-30 13:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_person_age_alter_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание изобпажения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Файл с изображениями')),
            ],
            managers=[
                ('obj_img', django.db.models.manager.Manager()),
            ],
        ),
    ]
